/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptanceFeeRouteImport } from './routes/acceptance-fee'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as ApplicationRouteImport } from './routes/application'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ScreeningSlipRouteImport } from './routes/screening-slip'
import { Route as SubmissionRouteImport } from './routes/submission'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCandidatesIdRouteImport } from './routes/admin.candidates.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptanceFeeRoute = AcceptanceFeeRouteImport.update({
  id: '/acceptance-fee',
  path: '/acceptance-fee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRoute = ApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningSlipRoute = ScreeningSlipRouteImport.update({
  id: '/screening-slip',
  path: '/screening-slip',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionRoute = SubmissionRouteImport.update({
  id: '/submission',
  path: '/submission',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesIdRoute = AdminCandidatesIdRouteImport.update({
  id: '/admin/candidates/$id',
  path: '/admin/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceptance-fee': typeof AcceptanceFeeRoute
  '/admission': typeof AdmissionRoute
  '/application': typeof ApplicationRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/eligibility': typeof EligibilityRoute
  '/payment': typeof PaymentRoute
  '/review': typeof ReviewRoute
  '/screening-slip': typeof ScreeningSlipRoute
  '/submission': typeof SubmissionRoute
  '/verify': typeof VerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceptance-fee': typeof AcceptanceFeeRoute
  '/admission': typeof AdmissionRoute
  '/application': typeof ApplicationRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/eligibility': typeof EligibilityRoute
  '/payment': typeof PaymentRoute
  '/review': typeof ReviewRoute
  '/screening-slip': typeof ScreeningSlipRoute
  '/submission': typeof SubmissionRoute
  '/verify': typeof VerifyRoute
  '/admin': typeof AdminIndexRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceptance-fee': typeof AcceptanceFeeRoute
  '/admission': typeof AdmissionRoute
  '/application': typeof ApplicationRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/eligibility': typeof EligibilityRoute
  '/payment': typeof PaymentRoute
  '/review': typeof ReviewRoute
  '/screening-slip': typeof ScreeningSlipRoute
  '/submission': typeof SubmissionRoute
  '/verify': typeof VerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceptance-fee'
    | '/admission'
    | '/application'
    | '/dashboard'
    | '/documents'
    | '/eligibility'
    | '/payment'
    | '/review'
    | '/screening-slip'
    | '/submission'
    | '/verify'
    | '/admin/'
    | '/admin/candidates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceptance-fee'
    | '/admission'
    | '/application'
    | '/dashboard'
    | '/documents'
    | '/eligibility'
    | '/payment'
    | '/review'
    | '/screening-slip'
    | '/submission'
    | '/verify'
    | '/admin'
    | '/admin/candidates/$id'
  id:
    | '__root__'
    | '/'
    | '/acceptance-fee'
    | '/admission'
    | '/application'
    | '/dashboard'
    | '/documents'
    | '/eligibility'
    | '/payment'
    | '/review'
    | '/screening-slip'
    | '/submission'
    | '/verify'
    | '/admin/'
    | '/admin/candidates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptanceFeeRoute: typeof AcceptanceFeeRoute
  AdmissionRoute: typeof AdmissionRoute
  ApplicationRoute: typeof ApplicationRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  EligibilityRoute: typeof EligibilityRoute
  PaymentRoute: typeof PaymentRoute
  ReviewRoute: typeof ReviewRoute
  ScreeningSlipRoute: typeof ScreeningSlipRoute
  SubmissionRoute: typeof SubmissionRoute
  VerifyRoute: typeof VerifyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCandidatesIdRoute: typeof AdminCandidatesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptance-fee': {
      id: '/acceptance-fee'
      path: '/acceptance-fee'
      fullPath: '/acceptance-fee'
      preLoaderRoute: typeof AcceptanceFeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application': {
      id: '/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof ApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening-slip': {
      id: '/screening-slip'
      path: '/screening-slip'
      fullPath: '/screening-slip'
      preLoaderRoute: typeof ScreeningSlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission': {
      id: '/submission'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof SubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates/$id': {
      id: '/admin/candidates/$id'
      path: '/admin/candidates/$id'
      fullPath: '/admin/candidates/$id'
      preLoaderRoute: typeof AdminCandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptanceFeeRoute: AcceptanceFeeRoute,
  AdmissionRoute: AdmissionRoute,
  ApplicationRoute: ApplicationRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  EligibilityRoute: EligibilityRoute,
  PaymentRoute: PaymentRoute,
  ReviewRoute: ReviewRoute,
  ScreeningSlipRoute: ScreeningSlipRoute,
  SubmissionRoute: SubmissionRoute,
  VerifyRoute: VerifyRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCandidatesIdRoute: AdminCandidatesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
